gitConfig:
  pull.rebase: "true"

image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: ignore

tasks:
  - name: Build Judger
    before: mkdir build && cd build && cmake .. && make
    init: sudo make install

vscode:
  extensions:
    - donjayamanne.githistory
    - eamodio.gitlens
    - golang.Go
    - gruntfuggly.todo-tree
    - humao.rest-client
    - ms-azuretools.vscode-docker
    - ms-vscode.cmake-tools
    - pkief.material-icon-theme
